from enum import Enum


class JsonField(Enum):
    ADDRESS = "address"
    AGENCY = "agency"
    AREA_IN_SQUARE_METERS = "areaInSquareMeters"
    CITY = "city"
    CURRENCY = "currency"
    DATA = "data"
    DATE_CREATED_FIRST = "dateCreatedFirst"
    ESTATE = "estate"
    ID = "id"
    IS_EXCLUSIVE_OFFER = "isExclusiveOffer"
    IS_PRIVATE_OWNER = "isPrivateOwner"
    IS_PROMOTED = "isPromoted"
    ITEMS = "items"
    LOCATION = "location"
    LOCATION_LABEL = "locationLabel"
    NAME = "name"
    OFFERS = "offers"
    PAGE_PROPS = "pageProps"
    PRICE_PER_SQUARE_METER = "pricePerSquareMeter"
    PROVINCE = "province"
    RENT_PRICE = "rentPrice"
    ROOMS_NUMBER = "roomsNumber"
    SEARCH_ADS = "searchAds"
    STREET = "street"
    TERRAIN_AREA_IN_SQUARE_METERS = "terrainAreaInSquareMeters"
    TITLE = "title"
    TOTAL_PRICE = "totalPrice"
    TRANSACTION = "transaction"
    VALUE = "value"
    RESULTS = "results"
    LONGITUDE = "lon"
    LATITUDE = "lat"
    COUNTRY = "country"
    STATE = "state"
    DISTRICT = "district"
    POSTCODE = "postcode"
